from typing import TypedDict, Optional, List


class DataAnalystState(TypedDict, total=False):
    """
    Shared state passed through the LangGraph nodes of the data analyst subagent.
    This is what your Deep Agent will pass in / receive back.
    """
    # Inputs from Deep Agent / backend
    file_path: str                  # absolute or relative path to uploaded csv/xls
    user_request: str               # "Create an EDA dashboard", etc.

    # Post-validation user request (rewritten to match dataset columns)
    validated_request: str

    # Validator outputs
    validation_columns: List[str]
    validation_missing_columns: List[str]
    validation_warnings: List[str]

    # Generated artifacts
    code: str                       # Python code generated by the LLM
    html_content: str               # The final dashboard.html content
    html_path: str                  # Where the HTML was written (inside sandbox or local)
    
    # Diagnostics
    error: Optional[str]            # Error message if something goes wrong
    logs: List[str]                 # Optional: internal debug logs
